# Generated by Django 4.0.3 on 2022-04-10 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_groupproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupproject',
            name='members',
        ),
        migrations.AddField(
            model_name='groupproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
