# Generated by Django 4.0.3 on 2022-04-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_grouptask_alter_taskuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.groupproject'),
        ),
    ]
