# Generated by Django 4.0.3 on 2022-04-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_grouptask_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptask',
            old_name='assigned_to',
            new_name='assignedTo',
        ),
    ]
